"""Keyword rules and embedding exemplars for the local intent classifier.

Latin-script entries are regular-expression fragments matched on word boundaries.
Devanagari and Kannada entries are matched as plain substrings, because Kannada in
particular glues case endings onto the word.

The exemplars must never repeat an utterance from `eval/`: a test enforces that.
"""

from enum import StrEnum


class Intent(StrEnum):
    BOOKING = "booking"
    TRIAGE = "triage"
    RECORDS = "records"
    SUPPORT = "support"
    GENERAL = "general"


# (pattern, weight). 1 = a hint, 2 = a clear signal, 3 = unambiguous.
KEYWORDS: dict[Intent, list[tuple[str, int]]] = {
    Intent.BOOKING: [
        (r"appointments?", 2),
        (r"book(ing|ed)?", 2),
        (r"slots?", 2),
        (r"reschedul\w*", 3),
        (r"cancel\w*", 2),
        (r"postpone\w*", 2),
        (r"availab\w+", 1),
        (r"free", 1),
        (r"shift", 1),
        (r"(see|meet|consult)\b.{0,20}\b(doctor|dr|specialist)", 2),
        (r"samay chahiye", 2),
        ("अपॉइंटमेंट", 2),
        ("अपाइंटमेंट", 2),
        ("अप्वाइंटमेंट", 2),
        ("मिलने का समय", 2),
        ("समय चाहिए", 2),
        ("बुक", 2),
        ("रद्द", 2),
        ("उपलब्ध", 1),
        ("ಅಪಾಯಿಂಟ್", 2),
        ("ಬುಕ್", 2),
        ("ರದ್ದು", 2),
        ("ಭೇಟಿ", 2),
        ("ಸಮಯ ಬೇಕು", 2),
        ("ಸಿಗುತ್ತಾರೆ", 1),
    ],
    Intent.TRIAGE: [
        (r"pain\w*", 2),
        (r"ach(e|es|ing)", 2),
        (r"headache", 2),
        (r"hurt\w*", 2),
        (r"fever", 2),
        (r"cough\w*", 2),
        (r"rash\w*", 2),
        (r"dizz\w*", 2),
        (r"nause\w*", 2),
        (r"vomit\w*", 2),
        (r"breath\w*", 2),
        (r"swelling|swollen", 2),
        (r"itch\w*", 2),
        (r"bleed\w*", 2),
        (r"symptom\w*", 2),
        (r"injur\w*", 2),
        (r"which (department|doctor)", 1),
        (r"dard", 2),
        (r"bukh?aar?", 2),
        (r"kha+nsi", 2),
        (r"chakkar", 2),
        (r"ulti", 2),
        (r"khujli", 2),
        (r"(kaunse|kaun se|kis) (doctor|department|vibhag)", 1),
        (r"jwara", 2),
        (r"novv?u", 2),
        (r"kemmu", 2),
        (r"va+nti", 2),
        (r"yaava (department|doctor|vibhaga)", 1),
        ("दर्द", 2),
        ("बुखार", 2),
        ("खांसी", 2),
        ("खाँसी", 2),
        ("उल्टी", 2),
        ("खुजली", 2),
        ("दाने", 2),
        ("चक्कर", 2),
        ("सूजन", 2),
        ("किस विभाग", 1),
        ("किस डॉक्टर", 1),
        ("ಜ್ವರ", 2),
        ("ಕೆಮ್ಮು", 2),
        ("ನೋವು", 2),
        ("ನೋಯು", 2),
        ("ವಾಂತಿ", 2),
        ("ತುರಿಕೆ", 2),
        ("ಊತ", 2),
        ("ಯಾವ ವಿಭಾಗ", 1),
    ],
    Intent.RECORDS: [
        (r"prescri\w+", 3),
        (r"(last|previous|past) (visit|time|consultation)", 2),
        (r"history", 2),
        (r"records?", 2),
        (r"reports?", 2),
        (r"medicines?|medication|tablets?", 1),
        (r"parchi", 2),
        (r"pichl[ie] ba+r", 2),
        (r"dawai?|davai", 1),
        (r"hindina", 2),
        (r"(koneya?|kaleda) baari", 2),
        ("पर्ची", 3),
        ("पिछली बार", 2),
        ("पिछली", 1),
        ("रिपोर्ट", 2),
        ("इतिहास", 2),
        ("दवा", 1),
        ("ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್", 3),
        ("ಕೊನೆಯ ಬಾರಿ", 2),
        ("ಕಳೆದ ಬಾರಿ", 2),
        ("ಹಿಂದಿನ", 1),
        ("ವರದಿ", 2),
        ("ಔಷಧ", 1),
    ],
    Intent.SUPPORT: [
        (r"timings?", 2),
        (r"opd", 2),
        (r"open(s|ing)?|closed?|closing", 2),
        (r"where", 2),
        (r"locat\w+|floor|address|directions?", 2),
        (r"emergency", 2),
        (r"contact|phone|helpline", 2),
        (r"number", 1),
        (r"hours", 1),
        (r"kaha+n?", 2),
        (r"khula|band", 2),
        (r"elli(de)?", 2),
        ("ओपीडी", 2),
        ("कहाँ", 2),
        ("कहां", 2),
        ("आपातकालीन", 2),
        ("इमरजेंसी", 2),
        ("समय क्या", 2),
        ("खुला", 2),
        ("नंबर", 1),
        ("ಓಪಿಡಿ", 2),
        ("ಎಲ್ಲಿ", 2),
        ("ತುರ್ತು", 2),
        ("ಸಮಯ ಏನು", 2),
        ("ಸಂಪರ್ಕ", 1),
        ("ಸಂಖ್ಯೆ", 1),
    ],
    Intent.GENERAL: [
        (r"hello|hi|hey", 2),
        (r"thanks?", 2),
        (r"good (morning|afternoon|evening|night)", 2),
        (r"bye|goodbye", 2),
        (r"namaste|namaskara?", 2),
        (r"shukriya|dhanyavaa?da?", 2),
        ("धन्यवाद", 2),
        ("नमस्ते", 2),
        ("शुक्रिया", 2),
        ("ಧನ್ಯವಾದ", 2),
        ("ನಮಸ್ಕಾರ", 2),
    ],
}


# Short paraphrases the embedding model compares against when the keywords are unsure.
EXEMPLARS: dict[Intent, list[str]] = {
    Intent.BOOKING: [
        "Book a doctor's appointment",
        "I want to schedule a visit with a doctor",
        "Cancel my booking",
        "Change the date of my appointment",
        "Is the doctor available on that day?",
        "डॉक्टर से मिलने का समय तय करना है",
        "मेरी बुकिंग की तारीख बदलनी है",
        "ಡಾಕ್ಟರ್ ಅನ್ನು ನೋಡಲು ಸಮಯ ನಿಗದಿ ಮಾಡಿ",
        "ನನ್ನ ಬುಕಿಂಗ್ ದಿನಾಂಕ ಬದಲಿಸಿ",
        "doctor ka time chahiye",
        "booking cancel kar do",
        "doctor na time beku",
    ],
    Intent.TRIAGE: [
        "I am not feeling well and have these symptoms",
        "I have pain in my body",
        "Which specialist treats this health problem?",
        "I feel sick and weak",
        "I got injured and it is swelling",
        "मेरी तबीयत ठीक नहीं है",
        "शरीर में तकलीफ है, किसे दिखाऊँ",
        "ನನಗೆ ಆರೋಗ್ಯ ಸರಿ ಇಲ್ಲ",
        "ಈ ತೊಂದರೆಗೆ ಯಾವ ಡಾಕ್ಟರ್",
        "tabiyat kharab hai",
        "nanage hushar illa",
    ],
    Intent.RECORDS: [
        "Show my medical history",
        "What happened in my earlier consultations?",
        "My past visits and the medicines I was given",
        "Get my lab report",
        "मेरा पुराना इलाज का रिकॉर्ड",
        "पहले कौन सी दवाइयाँ दी गई थीं",
        "ನನ್ನ ಹಳೆಯ ಚಿಕಿತ್ಸೆಯ ದಾಖಲೆ",
        "ಮೊದಲು ಕೊಟ್ಟ ಮಾತ್ರೆಗಳು ಯಾವುವು",
        "purana record dikhao",
        "hale report torisi",
    ],
    Intent.SUPPORT: [
        "When does the hospital open and close?",
        "How do I get to the hospital?",
        "Which floor is the department on?",
        "Phone number of the hospital",
        "Ambulance and emergency help line",
        "अस्पताल का पता और समय",
        "विभाग किस मंज़िल पर है",
        "ಆಸ್ಪತ್ರೆಯ ವಿಳಾಸ ಮತ್ತು ಸಮಯ",
        "ವಿಭಾಗ ಯಾವ ಮಹಡಿಯಲ್ಲಿದೆ",
        "hospital ka phone number",
        "aspatre address enu",
    ],
    Intent.GENERAL: [
        "Hello",
        "Good morning",
        "Thanks a lot",
        "Goodbye",
        "What can you help me with?",
        "Okay",
        "Tell me a joke",
        "नमस्ते",
        "शुक्रिया",
        "ನಮಸ್ಕಾರ",
    ],
}
